version: "3"

services:
  client:
    image: node:14.15.4
    working_dir: /client
    volumes:
      - ./client:/client
    command: "npm run dev"
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      